version: "3.8"
services:
    tensorboard:
        image: dl-tensorboard
        build:
            context: https://github.com/jelletreep/test-researchcloud/
            dockerfile: tensorboard.Dockerfile
        ports:
            - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
        volumes:
            - ${ROOT_DIR}:/jupyter
        command:
            [
                "tensorboard",
                "--logdir=${TENSORBOARD_DIR}",
                "--port=${TENSORBOARD_PORT}",
                "--bind_all",
            ]

    jupyter-server:
        image: dl-jupyter
        init: true
        build:
            context: https://github.com/jelletreep/test-researchcloud/
            dockerfile: jupyter.Dockerfile
        device_requests:
            - capabilities:
                - "gpu"
        env_file: https://raw.githubusercontent.com/jelletreep/test-researchcloud/main/.env
        ports:
            - ${JUPYTER_PORT}:${JUPYTER_PORT}
        volumes:
            - ${ROOT_DIR}:/jupyter
        command:
            [
                "jupyter",
                "notebook",
                "--ip=*",
                "--port=${JUPYTER_PORT}",
                "--allow-root",
                "--notebook-dir=${JUPYTER_DIR}",
                '--NotebookApp.token=${JUPYTER_TOKEN}'
            ]
